oauth:
  google:
    id: "google id"
    secret: "google secret"
    scopes:
      - "https://www.googleapis.com/auth/userinfo.email"
    endpoint:
      auth: "https://accounts.google.com/o/oauth2/auth"
      token: "https://oauth2.googleapis.com/token"

  github:
    id: "github id"
    secret: "github secret"
    scopes:
    endpoint:
      auth: "https://github.com/login/oauth/authorize"
      token: "https://github.com/login/oauth/access_token"

redirect:
  # This URL base is used to prepare callback URL for authentication server.
  # If omitted, then listen address is used. Should not contain scheme.
  oauth: "my.website.com:8080"
  # Redirect to this URL **after** successful authentication
  url: "/"

neofs:
  wallet:
    path: /path/to/wallet.json
    passphrase: '' # Passphrase to decrypt wallet. If you're using a wallet without a password, place '' here.
    address:  NfgHwwTi3wHAS8aFAN243C5vGbkYDpqLHP # Account address. If omitted default one will be used.
    