oauth:
  google:
    id: "google id"
    secret: "google secret"
    scopes:
      - "https://www.googleapis.com/auth/userinfo.email"
    endpoint:
      auth: "https://accounts.google.com/o/oauth2/auth"
      token: "https://oauth2.googleapis.com/token"

  github:
    id: "github id"
    secret: "github secret"
    scopes:
    endpoint:
      auth: "https://github.com/login/oauth/authorize"
      token: "https://github.com/login/oauth/access_token"

neofs:
  bearer_email_attribute: email # Exact name of the NeoFS attribute to be used for e-mail hash matching.
  bearer_user_id: NUVPACMnKFhpuHjsRjhUvXz1XhqfGZYVtY # If set, limits bearer token issued to the specified user ID.
  wallet:
    path: /path/to/wallet.json
    passphrase: '' # Passphrase to decrypt wallet. If you're using a wallet without a password, place '' here.
    address:  NfgHwwTi3wHAS8aFAN243C5vGbkYDpqLHP # Account address. If omitted default one will be used.
  cid: 2qAEwyRwV1sMmq8pc32mKCt1SRmTBXrzP9KbfMoHmqYM
  max_object_size: 209715200 # max object size allowed to be deployed via bearer token. 200mb.
  max_object_lifetime: "96h" # max object lifetime. 4 days.

peers:
  0:
    address: s01.neofs.devenv:8080
    priority: 1
    weight: 1

redirect:
  url:  "https://website.example.com/"

listen_address: 0.0.0.0:8083

logger:
  level: debug

bearer_cookie_name: "Bearer"

connect_timeout: 30s
request_timeout: 15s
rebalance_timer: 15s

prometheus:
  enabled: true
  address: localhost:9986
